export const DARK_MODE = "DARK_MODE";
export const OPEN_TOAST = "OPEN_TOAST";
export const CLOSE_TOAST = "CLOSE_TOAST";

export const SET_CURRENT_CITY = "SET_CURRENT_CITY";

export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";

export const FETCH_DATA_PENDING = 'FETCH_DATA_PENDING';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';

export const FIVE_DAYS_DATA_PENDING = 'FIVE_DAYS_DATA_PENDING';
export const FIVE_DAYS_DATA_SUCCESS = 'FIVE_DAYS_DATA_SUCCESS';
export const FIVE_DAYS_DATA_ERROR = 'FIVE_DAYS_DATA_ERROR';

export const SEARCH = "SEARCH";

export const FETCH_SUGGESTION_PENDING = "FETCH_SUGGESTION_PENDING";
export const FETCH_SUGGESTION_SUCCESS = "FETCH_SUGGESTION_SUCCESS";
export const FETCH_SUGGESTION_ERROR = "FETCH_SUGGESTION_ERROR";

export const OPEN_SUGGESTION_MENU = "OPEN_SUGGESTION_MENU";
export const CLOSE_SUGGESTION_MENU = "CLOSE_SUGGESTION_MENU";